### PR TITLE
reed solomon, covering, locally recoverable

### PR DESCRIPTION
**Pull request by mustafadgr**

### CODE REVIEW

**Comment by mustafadgr** [comment]
can you please review this check? I can't see how this failure is related to my commits. @valbert4

**Comment by mustafadgr** [comment]
> can you please review this last check? I can't see how this failure is related to my commits. @valbert4

I found the issue:

@AlexanderBarg commented previously that codes with availability should be parent of locally recoverable. but apparently in the current hierarchical structure, codes with availability is a descendant of locally recoverable, so if I add it as a parent in enters to an infinite loop. I am commenting that part for now.

**Comment by valbert4** [comment]
Very nice Mustafa; thanks for taking the time to do a thorough job.

**Comment by valbert4** [comment]
I've spread out your notes, which were very useful, into other entries. See comitt here: https://github.com/errorcorrectionzoo/eczoo_data/commit/2c9c43dbf3ce8a467c31f89d4658bcc6b25a356f

**Pull request merged**
