### PR TITLE
Balanced product codes

### PR DESCRIPTION
**Pull request by nikobreu**
Added details to balanced product code stub

### CODE REVIEW

**Comment by valbert4** [comment]
Thanks @nikobreu. I'll merge this with the contribution https://github.com/errorcorrectionzoo/eczoo_data/pull/35/files. It would be great if you could do (or at least outline) the harder tensor_product entry that would be a combination of homological, hypergraph, and tensor product codes. I'm guessing it's the same canonical tensor product of chain complexes for all three?

**Comment by nikobreu** [comment]
> Thanks @nikobreu. I'll merge this with the contribution https://github.com/errorcorrectionzoo/eczoo_data/pull/35/files. It would be great if you could do (or at least outline) the harder tensor_product entry that would be a combination of homological, hypergraph, and tensor product codes. I'm guessing it's the same canonical tensor product of chain complexes for all three?

Great, thanks!

And yes, they are all what is just called 'tensor product' in homological algebra. I'll take a look.

**Comment by valbert4** [comment]
@nikobreu thanks again, this is merged. qldpc codes are now in a subfolder inside qubits folder. Looking forward to your edits for code_id:homological_product! It's not clear whether homological_product or balanced_product should be the parent of the other; it's kind of like history (homo is parent) vs technical correctness (balanced is parent).

**Comment by valbert4** [comment]
PS Some parts of a student's entry for homological_product are commented out inside the yml file. Feel free to work that in.

**Pull request merged**
