### PR TITLE
Fixing compilation errors

### PR DESCRIPTION
**Pull request by noahberthusen**

### CODE REVIEW

**Comment by valbert4** [comment]
I see a wrong doi; use 10.1049/el:19931456

**Comment by noahberthusen** [comment]
doi:10.1049/el:19931456 was what it was before

**Comment by valbert4** [comment]
It's reading it as https://doi.org/10.1049/el_19931456. Try and play with how to get it to read ":" as ":" and not as "_". If you can't solve it, please tag phfaist .

**Comment by valbert4** [comment]
Thanks Noah!

**Pull request merged**
