### PR TITLE
Fix for issue #296

### PR DESCRIPTION
**Pull request by Sri-Harsha-T**
Created a bash script which generates all ancestors of a given code alongside their respective "physical" and "logical" parameters. The script creates a directory called the metadata and stores the ancestral table in a csv file along with displaying the table on the terminal.

## New Codes:

- ancestor.sh

References:
 \hyperref[code: https://github.com/gdbtek/linux-cookbooks/blob/master/libraries/util.bash]{ Bash function API to create tables}
#296

### CODE REVIEW

**Comment by valbert4** [comment]
Thanks, it works! I have two minor requests:
- There are duplicates in the table; to work with the table, those should be removed.
- "Phyical" is misspelled in the table. You can just do Physical and Logical to make the columns skinnier.
- Can you comment in your code where exactly you choose the "code_id" field to be the one to be listed in column 1 of the table? I need the flexibility to edit the code so another field is picked, such as e.g. the first 20 characters of the code name. I'm assuming the table will accommodate that?

Another request may be more complicated, so it's optional. But since you're such a bash whiz, maybe this is not so hard either.
- The 1st parent in the list of parents is the "primary parent". Is it possible to list all primary parents first in the table, delineating them from secondary parents?

**Comment by Sri-Harsha-T** [comment]
Hello, for the primary parent, should I consider the 1st level parents, as in the direct parents as the primary parent and the respective parents of the primary parents as the secondary ones? Or is it just the first parent in the list of the direct parents?

**Comment by valbert4** [comment]
First parent in the list of the direct parents. So for code X, it's primary
parent is the first of it's parents. The primary grandparent is the primary
parent of that parent. Etc.

**Comment by Sri-Harsha-T** [comment]
@valbert4 I have opened PR #303 after making necessary changes, could you please verify whether you are satisfied with the changes?

**Comment by valbert4** [comment]
Thanks, works great. Why is it working so much faster in this 2nd iteration?

**Pull request closed without merging**
